subarch: amd64
version_stamp: @TIMESTAMP@
rel_type: default
snapshot: @TIMESTAMP@
compression_mode: pixz

# The target specifies what target we want catalyst to do.  For building a CD,
# we start with livecd-stage1 as our target.
# example:
target: livecd-stage1

# This is the system profile to be used by catalyst to build this target.  It is
# specified as a relative path from /var/db/repos/gentoo/profiles.
# profile: default/linux/amd64/17.1/hardened
profile: default/linux/amd64/17.1/hardened

# This specifies where the seed stage comes from for this target,  The path is
# relative to $clst_sharedir/builds.  The rel_type is also used as a path prefix
# for the seed.
source_subpath: default/stage3-amd64-hardened-openrc-@TIMESTAMP@.tar.xz
 
# This is an optional directory containing portage configuration files.  It
# follows the same syntax as /etc/portage and should be consistent across all
# targets to minimize problems.
portage_confdir: @REPO_DIR@/../specs/portage/livegui

# This option specifies the location of the ebuild repositories that you would
# like to have used when building this target. It takes a space-separated list
# of directory names.
# example:
# repos: @REPO_DIR@/../overlays/guru @REPO_DIR@/../overlays/r7l-overlay @REPO_DIR@/../overlays/haskell
repos: @REPO_DIR@/../overlays/guru @REPO_DIR@/../overlays/mschiff 

# This allows the optional directory containing the output packages for
# catalyst.  Mainly used as a way for different spec files to access the same
# cache directory.  Default behavior is for this location to be autogenerated
# by catalyst based on the spec file.
pkgcache_path: @REPO_DIR@/../catalyst/packages/default

livecd/use:
	-aac
	compile-locales
	fbcon
	jpeg2k
	livecd
	networkmanager
	openexr
	opus
	postproc
	portaudio
	pulseaudio
	python
	theora
	vpx
	xetex
	minizip
	cups
	gtk
	gtk3
	text
	dbus
	jpeg
	icu
	X
	-wayland
	-kde
	-gnome
	-elogind
	-selinux
	-systemd
	server

#USE="dbus nightly" emerge  eww rofi playerctl brightnessctl dunst 
# feh networkmanager x11-misc/greenclip-bin alacritty picom app-misc/jq 
# maim x11-misc/xclip mpv

livecd/packages:
	# wm comparison - https://l3net.wordpress.com/2013/03/17/a-memory-comparison-of-light-linux-desktops/
	# Xorg base
	sys-auth/seatd
	x11-base/xorg-server
	x11-apps/xrandr

	# jwm base - https://github.com/astsu777/dotfiles
	x11-wm/jwm
	x11-misc/menumaker
	# x11-misc/tint2
	media-fonts/noto
	media-fonts/noto-cjk
	x11-libs/fltk # for jwm-settings-manager https://github.com/ZwerG-MaX/jwm-settings-manager

	# dwm base - https://github.com/ayamir/dotfiles/tree/master/gruvbox
	# x11-wm/dwm
	# x11-misc/dmenu
	# x11-terms/alacritty
	# x11-misc/dunst
	# app-misc/neofetch
	# app-shells/fish
	# sys-process/htop
	# x11-terms/kitty
	# app-misc/macchina
	# media-sound/mpd
	# media-sound/ncmpcpp
	# x11-misc/polybar
	# x11-misc/rofi
	# x11-terms/wezterm
	# x11-misc/picom
	# app-text/zathura

	# awesome base - https://github.com/ayamir/dotfiles/tree/master/catppuccin
	# x11-wm/awesome -> dwm-po custom compile
	# sys-process/btop
	# x11-misc/dunst
	# app-misc/fastfetch
	# app-shells/fish
	# sys-process/htop
	# x11-terms/kitty
	# app-misc/macchina
	# media-sound/mpd
	# media-sound/ncmpcpp
	# x11-misc/polybar
	# x11-misc/rofi
	# x11-terms/wezterm
	# x11-misc/nitrogen
	# x11-misc/picom
	# x11-misc/copyq
	# x11-misc/stalonetray
	# dev-libs/yajl
	# media-sound/cava
	# media-fonts/liberation-fonts

	# Net Driver
	net-misc/dhcp

	# gui applications
	net-misc/connman-ui
	net-misc/connman-notify
	x11-terms/alacritty
	x11-misc/pcmanfm
	net-im/telegram-desktop
	app-admin/conky
	# games-emulation/dosbox-staging
	x11-misc/synergy
	net-irc/hexchat
	net-misc/remmina
	# net-misc/seafile-client
	net-misc/tigervnc
	# net-p2p/deluge
	dev-util/pycharm-community
	app-editors/logseq-desktop-bin

	# gui memo apps
	# app-text/obsidian
	
	# internet browser
	www-client/vivaldi-snapshot

	# editors
	app-editors/vscodium
	dev-util/meld

	# virtualization
	app-containers/docker 
	app-containers/docker-compose
	
	# korean languages
	app-i18n/scim
	app-i18n/scim-bridge
	app-i18n/scim-hangul
	media-fonts/nanumfont 
	media-fonts/nanum
	media-fonts/noto-cjk	
	media-fonts/unfonts	
	media-fonts/unfonts-extra
	media-fonts/baekmuk-fonts

	# base commandline apps	
	app-misc/task
	app-arch/bzip2
	app-arch/cpio
	app-arch/dpkg
	app-arch/deb2targz
	app-arch/gzip
	app-arch/mt-st
	app-arch/pbzip2
	app-arch/rpm
	app-arch/tar
	app-arch/zip
	app-arch/unrar
	app-editors/nano
	app-editors/vim
	app-eselect/eselect-repository
	app-misc/colordiff
	app-misc/screen
	app-shells/bash-completion
	app-shells/gentoo-bashcomp
	app-vim/gentoo-syntax
	dev-lang/perl
	dev-lang/python
	dev-vcs/git
	dev-vcs/subversion
	net-analyzer/nmap
	net-dialup/minicom
	net-irc/hexchat
	net-misc/chrony
	net-misc/openssh
	net-misc/rsync
	net-misc/wget
	net-misc/whois
	app-misc/livecd-tools
	sys-apps/arch-chroot
	sys-apps/acl
	sys-apps/attr
	sys-apps/busybox
	sys-apps/coreutils
	sys-apps/diffutils
	sys-apps/dmidecode
	sys-apps/file
	sys-apps/findutils
	sys-apps/flashrom
	sys-apps/gawk
	sys-apps/hdparm
	sys-apps/hwinfo
	sys-apps/ipmitool
	sys-apps/iproute2
	sys-apps/inxi
	sys-apps/less
	sys-apps/man-db
	sys-apps/man-pages
	sys-apps/man-pages-posix
	sys-apps/memtester
	sys-apps/memtest86+
	sys-apps/mlocate
	sys-apps/netplug
	sys-apps/nvme-cli
	sys-apps/pciutils
	sys-apps/pcmciautils
	sys-apps/sdparm
	sys-apps/sed
	sys-apps/setserial
	sys-apps/smartmontools
	sys-apps/which
	sys-apps/usbutils
	sys-apps/util-linux
	sys-auth/ssh-import-id
	#sys-block/gparted
	sys-boot/grub
	sys-fs/cryptsetup
	sys-fs/fuse-exfat
	sys-fs/genfstab
	sys-fs/growpart
	sys-fs/lvm2
	sys-fs/ntfs3g
	sys-fs/reiserfsprogs
	sys-fs/xfsprogs
	sys-kernel/linux-firmware
	sys-process/htop
	sys-process/lsof
